"""this is so confusing

Revision ID: 4936a4751c7d
Revises: 420e66b85fef
Create Date: 2024-08-21 12:36:58.159636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4936a4751c7d'
down_revision = '420e66b85fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_item_images')
    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(
            'fk_items_category',  # Name for the foreign key constraint
            'categories',
            ['category_id'],
            ['id']
        )
        batch_op.drop_column('item_type')
        batch_op.drop_column('item_category')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('match_score',
               existing_type=sa.FLOAT(),
               type_=sa.DECIMAL(precision=5, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_is_read', ['is_read'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('contact_info', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('contact_info')
        batch_op.drop_column('is_anonymous')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_is_read')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('match_score',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_category', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('item_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_items_category', type_='foreignkey')  # Use the correct constraint name
        batch_op.alter_column('image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('category_id')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('_alembic_tmp_item_images',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('item_id', sa.INTEGER(), nullable=False),
        sa.Column('image_url', sa.TEXT(), nullable=False),
        sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['items.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
