"""trying out some stuff

Revision ID: 6c6a4cdd52d1
Revises: 4936a4751c7d
Create Date: 2024-08-26 11:28:26.638690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6a4cdd52d1'
down_revision = '4936a4751c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('reporter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('reporter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
